INFO 2024-12-10 23:24:25,699 basehttp "GET /api/users/login/ HTTP/1.1" 200 4226
INFO 2024-12-10 23:24:30,218 basehttp "POST /api/users/login/ HTTP/1.1" 302 0
INFO 2024-12-10 23:24:30,224 basehttp "GET /home/ HTTP/1.1" 200 4625
INFO 2024-12-10 23:27:40,437 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\companies\models.py changed, reloading.
INFO 2024-12-10 23:27:41,645 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:27:50,639 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\companies\models.py changed, reloading.
INFO 2024-12-10 23:27:51,551 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:27:55,602 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\companies\models.py changed, reloading.
INFO 2024-12-10 23:27:56,691 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:28:05,365 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\companies\models.py changed, reloading.
INFO 2024-12-10 23:28:06,344 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:28:40,626 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\seekers\models.py changed, reloading.
INFO 2024-12-10 23:28:41,670 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:29:24,648 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\vacancies\models.py changed, reloading.
INFO 2024-12-10 23:29:25,664 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:29:32,143 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\vacancies\models.py changed, reloading.
INFO 2024-12-10 23:29:33,173 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:29:49,420 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\companies\models.py changed, reloading.
INFO 2024-12-10 23:29:50,387 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:30:29,110 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\seekers\models.py changed, reloading.
INFO 2024-12-10 23:30:30,067 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:30:48,994 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:30:52,161 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-12-10 23:30:52,190 basehttp "GET /api/docs/swagger/ HTTP/1.1" 200 4653
INFO 2024-12-10 23:30:52,320 basehttp "GET /api/schema/ HTTP/1.1" 200 9622
INFO 2024-12-10 23:30:57,797 basehttp "GET /home/ HTTP/1.1" 200 4522
INFO 2024-12-10 23:31:01,545 basehttp "GET /api/vacancies/ HTTP/1.1" 200 4712
INFO 2024-12-10 23:31:03,961 basehttp "GET /api/vacancies/2/ HTTP/1.1" 200 4894
INFO 2024-12-10 23:31:05,088 basehttp "GET /api/vacancies/2/update/ HTTP/1.1" 302 0
INFO 2024-12-10 23:31:05,097 basehttp "GET /api/vacancies/ HTTP/1.1" 200 5045
INFO 2024-12-10 23:31:06,155 basehttp "GET /api/vacancies/4/ HTTP/1.1" 200 4882
INFO 2024-12-10 23:31:06,781 basehttp "GET /api/vacancies/4/update/ HTTP/1.1" 200 6884
INFO 2024-12-10 23:31:15,805 basehttp "GET /home/ HTTP/1.1" 200 4522
INFO 2024-12-10 23:31:16,439 basehttp "GET /api/vacancies/ HTTP/1.1" 200 4712
INFO 2024-12-10 23:31:16,964 basehttp "GET /home/ HTTP/1.1" 200 4522
INFO 2024-12-10 23:32:51,402 basehttp "GET /api/companies/create/ HTTP/1.1" 200 5613
INFO 2024-12-10 23:32:55,307 basehttp "GET /api/vacancies/manager/applications/ HTTP/1.1" 200 6700
INFO 2024-12-10 23:32:59,172 basehttp "POST /api/vacancies/manager/applications/toggle-reviewed/2/ HTTP/1.1" 302 0
INFO 2024-12-10 23:32:59,181 basehttp "GET /api/vacancies/manager/applications/ HTTP/1.1" 200 6699
INFO 2024-12-10 23:32:59,745 basehttp "POST /api/vacancies/manager/applications/toggle-reviewed/2/ HTTP/1.1" 302 0
INFO 2024-12-10 23:32:59,787 basehttp "GET /api/vacancies/manager/applications/ HTTP/1.1" 200 6700
WARNING 2024-12-10 23:33:00,439 log Not Found: /resumes/resumes/Documentation_vLrmHns.odt
WARNING 2024-12-10 23:33:00,440 basehttp "GET /resumes/resumes/Documentation_vLrmHns.odt HTTP/1.1" 404 4364
INFO 2024-12-10 23:33:31,308 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\jumys\settings.py changed, reloading.
INFO 2024-12-10 23:33:32,234 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:33:34,911 basehttp "GET /api/vacancies/manager/applications/ HTTP/1.1" 200 6700
INFO 2024-12-10 23:33:37,022 basehttp "GET /resumes/resumes/Documentation_vLrmHns.odt HTTP/1.1" 200 28810
INFO 2024-12-10 23:33:54,733 basehttp "POST /api/vacancies/manager/applications/toggle-reviewed/2/ HTTP/1.1" 302 0
INFO 2024-12-10 23:33:54,746 basehttp "GET /api/vacancies/manager/applications/ HTTP/1.1" 200 6699
INFO 2024-12-10 23:33:55,241 basehttp "POST /api/vacancies/manager/applications/toggle-reviewed/2/ HTTP/1.1" 302 0
INFO 2024-12-10 23:33:55,251 basehttp "GET /api/vacancies/manager/applications/ HTTP/1.1" 200 6700
INFO 2024-12-10 23:49:37,227 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:51:37,527 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:51:50,935 basehttp "GET /api/seekers/profile/ HTTP/1.1" 302 0
WARNING 2024-12-10 23:51:50,947 log Not Found: /accounts/login/
WARNING 2024-12-10 23:51:50,948 basehttp "GET /accounts/login/?next=/api/seekers/profile/ HTTP/1.1" 404 4175
INFO 2024-12-10 23:51:52,706 basehttp "GET /api/seekers/profile/edit HTTP/1.1" 302 0
WARNING 2024-12-10 23:51:52,713 log Not Found: /accounts/login/
WARNING 2024-12-10 23:51:52,716 basehttp "GET /accounts/login/?next=/api/seekers/profile/edit HTTP/1.1" 404 4179
INFO 2024-12-10 23:51:53,523 basehttp "GET /api/seekers/profile/ HTTP/1.1" 302 0
INFO 2024-12-10 23:52:02,155 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-12-10 23:52:02,175 basehttp "GET /api/docs/swagger/ HTTP/1.1" 200 4653
INFO 2024-12-10 23:52:02,433 basehttp "GET /api/schema/ HTTP/1.1" 200 9622
INFO 2024-12-10 23:52:06,883 basehttp "GET /home/ HTTP/1.1" 200 3474
INFO 2024-12-10 23:52:08,051 basehttp "GET /api/users/login/ HTTP/1.1" 200 4226
ERROR 2024-12-10 23:52:12,658 log Internal Server Error: /api/users/login/
Traceback (most recent call last):
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: analytics_useractivity

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\users\views.py", line 125, in login_view
    login(request, user)
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\analytics\signals.py", line 7, in log_user_login
    UserActivity.objects.create(user=user)
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: analytics_useractivity
ERROR 2024-12-10 23:52:12,670 basehttp "POST /api/users/login/ HTTP/1.1" 500 178244
INFO 2024-12-10 23:52:39,303 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:52:41,944 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-12-10 23:52:41,983 basehttp "GET /api/docs/swagger/ HTTP/1.1" 200 4653
INFO 2024-12-10 23:52:42,201 basehttp "GET /api/schema/ HTTP/1.1" 200 9622
INFO 2024-12-10 23:52:45,577 basehttp "GET /home/ HTTP/1.1" 200 3474
INFO 2024-12-10 23:52:47,277 basehttp "GET /api/users/login/ HTTP/1.1" 200 4226
INFO 2024-12-10 23:52:51,829 basehttp "POST /api/users/login/ HTTP/1.1" 302 0
INFO 2024-12-10 23:52:51,837 basehttp "GET /home/ HTTP/1.1" 200 4625
WARNING 2024-12-10 23:52:56,666 log Not Found: /api/core/
WARNING 2024-12-10 23:52:56,667 basehttp "GET /api/core/ HTTP/1.1" 404 4130
INFO 2024-12-10 23:53:00,806 basehttp "GET /api/analytics HTTP/1.1" 301 0
INFO 2024-12-10 23:53:00,814 basehttp "GET /api/analytics/ HTTP/1.1" 200 4585
INFO 2024-12-10 23:53:02,832 basehttp "GET /api/analytics/users/role-distribution/ HTTP/1.1" 200 4325
INFO 2024-12-10 23:53:02,936 basehttp "GET /resumes/analytics_charts/user_role_distribution.png HTTP/1.1" 200 10072
INFO 2024-12-10 23:53:10,196 basehttp "GET /api/analytics/users/role-distribution/ HTTP/1.1" 200 4325
INFO 2024-12-10 23:53:10,253 basehttp "GET /resumes/analytics_charts/user_role_distribution.png HTTP/1.1" 200 10072
INFO 2024-12-10 23:53:18,880 basehttp "GET /api/analytics/users/login-activity/ HTTP/1.1" 200 4331
INFO 2024-12-10 23:53:18,942 basehttp "GET /resumes/analytics_charts/user_login_activity.png HTTP/1.1" 200 18962
INFO 2024-12-10 23:53:23,716 basehttp "GET /api/analytics/vacancies/applications/ HTTP/1.1" 200 4344
INFO 2024-12-10 23:53:23,771 basehttp "GET /resumes/analytics_charts/applications_per_vacancy.png HTTP/1.1" 200 16155
INFO 2024-12-10 23:53:36,768 basehttp "GET /api/analytics/abilities/distribution/ HTTP/1.1" 200 4337
INFO 2024-12-10 23:53:36,825 basehttp "GET /resumes/analytics_charts/abilities_distribution.png HTTP/1.1" 200 22812
INFO 2024-12-10 23:53:42,794 basehttp "GET /api/analytics/abilities/distribution/ HTTP/1.1" 200 4337
INFO 2024-12-10 23:53:42,863 basehttp "GET /resumes/analytics_charts/abilities_distribution.png HTTP/1.1" 200 22812
INFO 2024-12-10 23:53:43,989 basehttp "GET /api/analytics/vacancies/applications/ HTTP/1.1" 200 4344
INFO 2024-12-10 23:53:44,097 basehttp "GET /resumes/analytics_charts/applications_per_vacancy.png HTTP/1.1" 200 16155
INFO 2024-12-10 23:53:49,421 basehttp "GET /api/analytics/vacancies/applications/ HTTP/1.1" 200 4344
INFO 2024-12-10 23:53:49,485 basehttp "GET /resumes/analytics_charts/applications_per_vacancy.png HTTP/1.1" 200 16155
INFO 2024-12-10 23:57:11,203 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\analytics\views.py changed, reloading.
INFO 2024-12-10 23:57:12,410 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:57:21,848 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\analytics\views.py changed, reloading.
INFO 2024-12-10 23:57:22,859 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:57:37,500 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\analytics\urls.py changed, reloading.
INFO 2024-12-10 23:57:38,508 autoreload Watching for file changes with StatReloader
INFO 2024-12-10 23:57:56,447 basehttp "GET / HTTP/1.1" 302 0
INFO 2024-12-10 23:57:56,503 basehttp "GET /api/docs/swagger/ HTTP/1.1" 200 4653
INFO 2024-12-10 23:57:56,724 basehttp "GET /api/schema/ HTTP/1.1" 200 9622
INFO 2024-12-10 23:58:08,205 basehttp "GET /api/analytics/ HTTP/1.1" 200 4585
INFO 2024-12-10 23:58:51,165 basehttp "GET /api/analytics/ HTTP/1.1" 200 4677
ERROR 2024-12-10 23:58:51,993 log Internal Server Error: /api/analytics/vacancies/per-day/
Traceback (most recent call last):
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\analytics\views.py", line 142, in vacancies_per_day
    Vacancy.objects.filter(created_at__gte=start_date)
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\sql\query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KogSa\AppData\Local\pypoetry\Cache\virtualenvs\jumys-Y4X2CG5X-py3.12\Lib\site-packages\django\db\models\sql\query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_at' into field. Choices are: application, applications, bookmarked_users, company, company_id, currency, employment_type, id, is_active, location, location_id, position_name, position_name_id, salary_end, salary_start, technology
ERROR 2024-12-10 23:58:52,001 basehttp "GET /api/analytics/vacancies/per-day/ HTTP/1.1" 500 120414
INFO 2024-12-11 00:01:30,407 autoreload C:\Users\KogSa\OneDrive\Рабочий стол\projects\DjangoFall2024\Rroject\jumys\jumys\vacancies\models.py changed, reloading.
INFO 2024-12-11 00:01:31,541 autoreload Watching for file changes with StatReloader
INFO 2024-12-11 00:03:55,308 autoreload Watching for file changes with StatReloader
